[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dao_voting = "9qkB1pcntVosURAYkTzKznGM2KuGJR5A2PmXZyBrWir1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
